# Generated by Django 4.2.7 on 2023-11-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_post_category_post_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
